routes:
  - node_id: G
    max_created_date: 1614392990
  - node_id: F
    max_created_date: 1646260941
  - node_id: D
    max_created_date: 1680321520
  - node_id: C
    max_created_date: 1712427916
  - node_id: I
    max_created_date: 1742072468
default_node_id: H
